### ISSUE TITLE
Approve member should have a confirmation prompt

### ISSUE THREAD

**Issue by roberthunt** [NottingHack/hms#62]
The "Impending Payment" email contains a link to approve the member (hms/members/approveMember/<member_id>) but there is no confirmation before the member is approved. It is possible to accidentally click this link and the member will be approved, there should probably be a confirmation before the member has been approved.

Do we actually use this feature? I though that the bank statement import takes care of this is most cases.

Related to #49

**Comment by geeksareforlife** [comment]
@jamesfowkes does your PR fix this?  Maybe we should also take the link out of the email?

**Comment by dpslwk** [comment]
Im not sure PR #104 will cover this as thats all stuff on pages and not catching the direct links.
But yes since the CSV system was put in place the link in the email is redundant
template file is
hms/app/View/Emails/html/notify_admins_payment_incoming.ctp
