### ISSUE TITLE
Add ability to re-send the "Membership Complete" email

### ISSUE THREAD

**Issue by roberthunt** [NottingHack/hms#67]
I've just had to manually construct the "Membership Complete" email as a user accidentally deleted it. It would be useful if we can re-send it if a user deletes it or it goes missing.

**Comment by jamesfowkes** [comment]
I've pushed changes for the functionality, think it works OK. But the test for MembersController doesn't pass and I don't want to muck around with those until I know more about them,

Could someone check over my changes and run the tests, see what's up?
