### ISSUE TITLE
Adding "No AOL" message above membership sign-up

### ISSUE THREAD

**Issue by katemonkey** [NottingHack/hms#77]
Since AOL keeps on blocking all emails sent from HMS, there needs to be a message in the sign-up form.

I figure something like:

"Please note: Due to AOL repeatedly blocking emails from HMS, we cannot accept AOL email addresses."

Unless all y'all want to set up a checker to look for "aol.com" in the email address.

**Comment by roberthunt** [comment]
I've just created an AOL email account `nottinghack@aol.co.uk` which also includes `nottinghack@aol.com` and registered them both with HMS.
 
 * `nottinghack@aol.co.uk` - the email came through to the spam folder immediately.
 * `nottinghack@aol.com` - the email came through to the spam folder but it took around 10 minutes.

It appears to be working, yes the messages end up in the spam folder but they do get through. Are we sure people are not just ignoring their spam folder when looking for the message? I know we always tell them to check it when going through the signup process.

**Comment by katemonkey** [comment]
The last time it happened, this was the email that was sent back from AOL:

> This is the mail system at host andromeda.lwk.me.

> I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

> For further assistance, please send mail to postmaster.

> If you do so, please include this problem report. You can
delete your own text from the attached returned message.

 >                  The mail system

> <marypodd@aol.com>: host mailin-04.mx.aol.com[152.163.0.100] said: 521 5.2.1 :
    (CON:B1)  http://postmaster.info.aol.com/errors/554conb1.html (in reply to
    end of DATA command)

> Final-Recipient: rfc822; marypodd@aol.com
> Original-Recipient: rfc822;marypodd@aol.com
> Action: failed
> Status: 5.2.1
> Remote-MTA: dns; mailin-04.mx.aol.com
> Diagnostic-Code: smtp; 521 5.2.1 :  (CON:B1)
    http://postmaster.info.aol.com/errors/554conb1.html

When I look up that (Diagnostic Code)[http://postmaster.info.aol.com/errors/554conb1.html] it says:

> The IP address has been blocked due to a spike in unfavorable e-mail statistics.

The last time it happened, it was with both AOL.com adresses on 18/02.  An AOL.co.uk one went through without a hitch (I think - I haven't had any emails or complaints).

**Comment by roberthunt** [comment]
There is not really a fix for this other than to advise members to get in contact if they have trouble with their AOL email.
