### ISSUE TITLE
Possible issue with php/kbr5 used in vagrant

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms#79]
When doing
    $ vagrant up 
on the mac I'm seeing the following errors in the krb5 section
Any one else seeing this and is it causing issues?

    ==> default: patching file php_krb5_kadm.h
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=compile cc  -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2   -c /root/php-krb/krb5-1.0.0/krb5.c -o krb5.lo
    ==> default: libtool: compile:  cc -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -Wall -g -O2 -c /root/php-krb/krb5-1.0.0/krb5.c  -fPIC -DPIC -o .libs/krb5.o
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=compile cc  -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2   -c /root/php-krb/krb5-1.0.0/negotiate_auth.c -o negotiate_auth.lo
    ==> default: libtool: compile:  cc -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -Wall -g -O2 -c /root/php-krb/krb5-1.0.0/negotiate_auth.c  -fPIC -DPIC -o .libs/negotiate_auth.o
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=compile cc  -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2   -c /root/php-krb/krb5-1.0.0/gssapi.c -o gssapi.lo
    ==> default: libtool: compile:  cc -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -Wall -g -O2 -c /root/php-krb/krb5-1.0.0/gssapi.c  -fPIC -DPIC -o .libs/gssapi.o
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=compile cc  -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2   -c /root/php-krb/krb5-1.0.0/kadm.c -o kadm.lo
    ==> default: libtool: compile:  cc -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -Wall -g -O2 -c /root/php-krb/krb5-1.0.0/kadm.c  -fPIC -DPIC -o .libs/kadm.o
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=compile cc  -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2   -c /root/php-krb/krb5-1.0.0/kadm5_principal.c -o kadm5_principal.lo
    ==> default: libtool: compile:  cc -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -Wall -g -O2 -c /root/php-krb/krb5-1.0.0/kadm5_principal.c  -fPIC -DPIC -o .libs/kadm5_principal.o
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c: In function 'zim_KADM5Principal_load':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:179:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default:
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c: In function 'zim_KADM5Principal_save':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:216:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c: In function 'zim_KADM5Principal_changePassword':
    ==> default:
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:264:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c: In function 'zim_KADM5Principal_delete':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:289:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c: In function 'zim_KADM5Principal_rename':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:326:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:333:4: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_principal.c:340:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_principal.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=compile cc  -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2   -c /root/php-krb/krb5-1.0.0/kadm5_policy.c -o kadm5_policy.lo
    ==> default: libtool: compile:  cc -I. -I/root/php-krb/krb5-1.0.0 -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -Wall -g -O2 -c /root/php-krb/krb5-1.0.0/kadm5_policy.c  -fPIC -DPIC -o .libs/kadm5_policy.o
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_policy.c: In function 'zim_KADM5Policy_load':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_policy.c:160:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_policy.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_policy.c: In function 'zim_KADM5Policy_save':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_policy.c:188:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_policy.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_policy.c: In function 'zim_KADM5Policy_delete':
    ==> default: /root/php-krb/krb5-1.0.0/kadm5_policy.c:211:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
    ==> default: In file included from /root/php-krb/krb5-1.0.0/php_krb5.h:31:0,
    ==> default:                  from /root/php-krb/krb5-1.0.0/kadm5_policy.c:23:
    ==> default: /usr/include/php5/Zend/zend_exceptions.h:43:17: note: expected 'char *' but argument is of type 'const char *'
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=link cc -DPHP_ATOM_INC -I/root/php-krb/krb5-1.0.0/include -I/root/php-krb/krb5-1.0.0/main -I/root/php-krb/krb5-1.0.0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -Wall -g -O2  -Wl,-z,relro -lkadm5clnt_mit -lgssrpc -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -o krb5.la -export-dynamic -avoid-version -prefer-pic -module -rpath /root/php-krb/krb5-1.0.0/modules  krb5.lo negotiate_auth.lo gssapi.lo kadm.lo kadm5_principal.lo kadm5_policy.lo
    ==> default: libtool: link: cc -shared  -fPIC -DPIC  .libs/krb5.o .libs/negotiate_auth.o .libs/gssapi.o .libs/kadm.o .libs/kadm5_principal.o .libs/kadm5_policy.o   -lkadm5clnt_mit -lgssrpc -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err  -O2 -Wl,-z -Wl,relro   -Wl,-soname -Wl,krb5.so -o .libs/krb5.so
    ==> default: libtool: link: ( cd ".libs" && rm -f "krb5.la" && ln -s "../krb5.la" "krb5.la" )
    ==> default: /bin/bash /root/php-krb/krb5-1.0.0/libtool --mode=install cp ./krb5.la /root/php-krb/krb5-1.0.0/modules
    ==> default: libtool: install: cp ./.libs/krb5.so /root/php-krb/krb5-1.0.0/modules/krb5.so
    ==> default: libtool: install: cp ./.libs/krb5.lai /root/php-krb/krb5-1.0.0/modules/krb5.la
    ==> default: libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /root/php-krb/krb5-1.0.0/modules
    ==> default: ----------------------------------------------------------------------
    ==> default: Libraries have been installed in:
    ==> default:    /root/php-krb/krb5-1.0.0/modules
    ==> default:
    ==> default: If you ever happen to want to link against installed libraries
    ==> default: in a given directory, LIBDIR, you must either use libtool, and
    ==> default: specify the full pathname of the library, or use the `-LLIBDIR'
    ==> default: flag during linking and do at least one of the following:
    ==> default:    - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
    ==> default:      during execution
    ==> default:    - add LIBDIR to the `LD_RUN_PATH' environment variable
    ==> default:      during linking
    ==> default:    - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
    ==> default:    - have your system administrator add LIBDIR to `/etc/ld.so.conf'
    ==> default:
    ==> default: See any operating system documentation about shared libraries for
    ==> default: more information, such as the ld(1) and ld.so(8) manual pages.
    ==> default: ----------------------------------------------------------------------
    ==> default: Build complete.
    ==> default: Don't forget to run 'make test'.
    ==> default: Installing shared extensions:     /usr/lib/php5/20100525/
    ==> default: Installing header files:          /usr/include/php5/

**Comment by daniel1111** [comment]
Yeah, I’m pretty sure I see this too. seems to work ok though. We perhaps should look into why, but fixing it may mean maintaining our own version of the library.

**Comment by dpslwk** [comment]
Hmm looked again there just warning and fixed in on Sep 23, 2013 in at least on php banch
https://github.com/php/php-src/commit/f7eff9cd41e0b996af9a0a01d3c5f8fdd8b7fa60

Seems we running 5.4.36-0+deb7u3 in Vagrant which is latest for wheezy, but guess this hasn't made it there
