### ISSUE TITLE
Tool Bookings showing 1hr out on calendar

### ISSUE THREAD

**Issue by jamesfowkes** [NottingHack/hms#82]
When adding a booking to the laser, said booking is displaying +1hr later than booked time on main calendar view.
Under List/Cancel bookings, correct time is shown.

**Comment by dpslwk** [comment]
Sounds like a time zone issue


'RepRap' Matt

**Comment by jamesfowkes** [comment]
I agree.

Clashing bookings are still detected (and rejected) correctly based on actual time of booking.

**Comment by geeksareforlife** [comment]
It's weird, it's only on the default view - if you go forward a week and then back it is fine, which means that there is something wrong here, in ToolsToolsController.php:

````php
		if (isset($this->request->query['mon'])) {
			$monday = new DateTime($this->request->query['mon']);
		}
		else {
			$monday = $this->__getMonday();
		}
```

The else clause is the problem (it decides when monday is this week if not date is on the query line).  That function is:

```php
	private function __getMonday() {
		$date = new DateTime('now', new DateTimeZone('Europe/London'));
		$dayOfWeek = $date->format('N');
		// set the time to midnight
		$date->setTime(0,0,0);
		$offset = $dayOfWeek - 1;
		$date->sub(new DateInterval('P' . $offset . 'D'));
		return $date;
	}
```

But I can't see why this is wrong, and I can't get to a development machine until later this week.

J

**Comment by dpslwk** [comment]
See i was thinking it was the view

but form the code you posted you could try updating 

>           $monday = new DateTime($this->request->query['mon']);
 to include 
> , new DateTimeZone('Europe/London'
like the other DateTime queries, though i have also set the datetime default  in the php sever to Europe/London anyways

What i find interesting is the calendar view for a default has an extra row at the bottom, see attached images for pics of this week vs next






'RepRap' Matt

**Comment by geeksareforlife** [comment]
I take it back, it is the view - it is missing out 2am for some reason!

**Comment by geeksareforlife** [comment]
This is too weird, I need to be on a proper machine to figure it out

**Comment by Pyroka** [comment]
Is it because when it displays it in the view it increments by X amount of time and the clocks go back this Sunday? So at some point $date + 1 hour == $date

**Comment by geeksareforlife** [comment]
I hate time

**Comment by Pyroka** [comment]
Oh wait, stupid stupid stupid me.

It works last week and next week because America changed their clocks back this weekend

**Comment by Pyroka** [comment]
This gets even stranger. The getEventDiv is correct, it shows start_1400 for Matt Little's booking on Monday. Looks like it's the CSS/JS that makes that 'top: 1400px'

**Comment by Pyroka** [comment]
So yeah, it's the missing 2am (presumably from when the clocks changed) that's causing the issue getEventDiv is showing the correct start time (1400 for Matt Little's booking on Monday)

**Comment by dpslwk** [comment]
The following to urls give the same week view but one correctly calculates all the times the other does not
hms/tools/view/1
hms/tools/view/1?mon=2015-03-23T00%3A00%3A00%2B01%3A00

so this could be the _getMonday() function james mentioned 
or its in the view line 94-104, posible the $date->format

	$date = clone $monday;

	for ($i = 0; $i < 48; $i++) {

		echo('<tr>' . "\n");
		if ($i%2 == 0) {
			echo('<td class="time" rowspan="2">');
			echo('<span>' . $date->format('H:i') . '</span>');
			echo('</td>');
			$row = 'light';
		}


'RepRap' Matt

**Comment by Pyroka** [comment]
Interestingly it seems that when you don't specify the date, some of the code thinks that the clocks went forward at 1am on the 23rd, instead of 1am on the 29th (I can't get the bug to repro when specifying the date, even if I set it to the 29th).

I suspect it's the getMonday function, I'm just not sure why (but the missing 2am is just too telling)

**Comment by dpslwk** [comment]
Ok so this is interesting 

hms/tools/view/1

    $monday = object(DateTime)#71 (3) { ["date"]=> string(19) "2015-03-23 00:00:00" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/London" }

hms/tools/view/1?mon=2015-03-23T00%3A00%3A00%2B01%3A00

    $monday = object(DateTime)#71 (3) { ["date"]=> string(19) "2015-03-23 00:00:00" ["timezone_type"]=> int(1) ["timezone"]=> string(6) "+01:00" }

**Comment by Pyroka** [comment]
Found it!

It's in the view, starting around line 109:

```php
for ($j = 0; $j < 7; $j++) {
			if ($date > $now) {
				$class = ' class="' . $row . '"';
				$link =$this->Html->link("", array(
					'plugin'		=>	'Tools',
					'controller'	=>	'ToolsTools',
					'action'		=>	'addbooking',
					$tool['Tool']['tool_id'],
					'?'				=>	array(
						't'	=> $date->format(ToolsGoogle::DATETIME_STR),
						),
					));
			}
			else {
				$class = ' class="' . $row . ' past"';
				$link = '';
			}
			echo('<td' . $class . '>');
			echo($link);
			echo('</td>');
			$date->add(new DateInterval('P1D'));
		}
		$date->sub(new DateInterval('P7D'));
```

That bit where it adds 1 day 7 times then subtracts 7 days. When the time is correct, adding 7 days takes you to sunday where the clocks change, then when you subtract 7 days you end up an hour ahead of where you were meant to be.

Repo case:

```php
$date = new DateTime('now', new DateTimeZone('Europe/London'));
$dayOfWeek = $date->format('N');
// set the time to midnight
$date->setTime(0,0,0);
$offset = $dayOfWeek - 1;
$date->sub(new DateInterval('P' . $offset . 'D'));
print_r($date);

for ($i = 0; $i < 48; $i++) {
	//if ($i%2 == 0) {
		echo($date->format('H:i'));
		echo("\n");
	//}
	for ($j = 0; $j < 7; $j++) {
		$date->add(new DateInterval('P1D'));
	}
	$date->sub(new DateInterval('P7D'));
	$date->add(new DateInterval('PT30M'));
}
```

You can run that here: http://writecodeonline.com/php/

If you comment out that second loop and the subtract 7 days it's fixed

Can't repo it when specifying the date even if I set it to the 1st March (American clocks changed on the 8th) but that's likely because of the timezone thing that Matt just posted.

I love time-zones :D

**Comment by geeksareforlife** [comment]
I'm awesome at dates, they love me so much!

**Comment by geeksareforlife** [comment]
Now I just need to work at a way to generate that table properly.

**Comment by Pyroka** [comment]
Edit: So this is a bug in DateInterval then? It applies the extra hour going forward but not going back?

**Comment by geeksareforlife** [comment]
When you set the date, the timezone is set to +0100, which has no daylight savings!

Yeah, it looks like it accounts for the extra hour going forward, but not on the way back.

This might be fixable by not adding a day in the seventh iteration and only subtracting 6 days?

**Comment by geeksareforlife** [comment]
As we always start the calendar on a monday, and the clocks always change after midnight on a sunday, this should avoid it?

**Comment by Pyroka** [comment]
Surely the quickest fix is that before the 'day' loop (```$j < 7```) you should clone $date to some new var and add the days to that, then you can remove the problematic 'subtract 7 days' line

**Comment by geeksareforlife** [comment]
Yes, that is a much better idea

**Comment by geeksareforlife** [comment]
Can someone with access to Holly patch the ToolsTools/view.ctp, replacing this:

```php
		for ($j = 0; $j < 7; $j++) {
			if ($date > $now) {
				$class = ' class="' . $row . '"';
				$link =$this->Html->link("", array(
					'plugin'		=>	'Tools',
					'controller'	=>	'ToolsTools',
					'action'		=>	'addbooking',
					$tool['Tool']['tool_id'],
					'?'				=>	array(
						't'	=> $date->format(ToolsGoogle::DATETIME_STR),
						),
					));
			}
			else {
				$class = ' class="' . $row . ' past"';
				$link = '';
			}
			echo('<td' . $class . '>');
			echo($link);
			echo('</td>');
			$date->add(new DateInterval('P1D'));
		}
		$date->sub(new DateInterval('P7D'));
```

with this:

```php
		$newdate = clone $date;
		for ($j = 0; $j < 7; $j++) {
			if ($date > $now) {
				$class = ' class="' . $row . '"';
				$link =$this->Html->link("", array(
					'plugin'		=>	'Tools',
					'controller'	=>	'ToolsTools',
					'action'		=>	'addbooking',
					$tool['Tool']['tool_id'],
					'?'				=>	array(
						't'	=> $newdate->format(ToolsGoogle::DATETIME_STR),
						),
					));
			}
			else {
				$class = ' class="' . $row . ' past"';
				$link = '';
			}
			echo('<td' . $class . '>');
			echo($link);
			echo('</td>');
			$newdate->add(new DateInterval('P1D'));
		}
```

And commit this change to master too.  But don't push master to Holly, that could open a whole bag of poo.

**Comment by geeksareforlife** [comment]
Also, @Pyroka - I miss you!

**Comment by dpslwk** [comment]
yeah that didn’t work
see hms, its live 

'RepRap' Matt

**Comment by dpslwk** [comment]
nvm fixed it

'RepRap' Matt

**Comment by Pyroka** [comment]
:D This bug was just to fun to pass-up

**Comment by dpslwk** [comment]
Of course it's now broken if we go forward a week then back again
as this section 

    // previous week link
    $date = clone $monday;
    $date->sub(new DateInterval('P7D'));
    $previous = array(
    	'alt'	=> 'Previous Week',
    	'title'	=> 'Previous Week',
    	'class' => 'navleft',
    	'url'	=> array(
    		'plugin'		=>	'Tools',
    		'controller'	=>	'ToolsTools',
    		'action'		=>	'view',
    		$tool['Tool']['tool_id'],
    		'?'				=>	array(
    			'mon'	=> $date->format(ToolsGoogle::DATETIME_STR),
    			),
    		),
    	);

Does a smiler thing and not remove the Timezone from the interval in the past

**Comment by geeksareforlife** [comment]
Why is it broken?  It looks like it works to me

**Comment by Pyroka** [comment]
That doesn't look broken to me? I can't ever get it to show when 'mon' is specified (presumably because of the timezone)

**Comment by dpslwk** [comment]
hms/tools/view/1?mon=2015-03-23T00%3A00%3A00%2B01%3A00

The times down the side are correct but the past shading is an hour in advance and all the links have TZ of +01:00, not just the one on the sunday

**Comment by geeksareforlife** [comment]
Ok, revert the change and let me look at it again.

**Comment by Pyroka** [comment]
Fucking shitty PHP date functions :(

The shading is incorrect for me but I'm not sure if the Timezone on the links is a bad thing, depends what time-zone google assumes they're in (likely, google handles that you can specify the time-zone and does the correct thing, storing it internally as UTC time and then localising it when displaying it)

If you try to book with one of these messes up times does it show up on the calendar at the wrong time?

**Comment by geeksareforlife** [comment]
It seems to book in the correct time in the actual calendar.  I'm not sure the timezone in the link is a bad thing either

**Comment by Pyroka** [comment]
I wonder if sub 'P7D' works if you convert the time to UTC before and back after

**Comment by geeksareforlife** [comment]
I can't understand why the shading would work now and not with thee new code

**Comment by dpslwk** [comment]
Right now I’m thinking the whole previous and next things could be done so much cleaner 

We should just pass 

    view/1?week=+1

or 

    view/1?week=-2

pass $currentWeek to the view so it can calculate the links with out any date math

and have the controller work out the $monday from that using the _getMonday() function with add sub number of weeks and possible UTC work around in there

also means we sanitise the calendar request so it always starts a midnight, as this currently works and just screws up all sorts

    https://lspace.nottinghack.org.uk/hms/tools/view/1?mon=2015-03-23T12%3A00%3A00%2B01%3A00

Thoughts?


'RepRap' Matt

**Comment by geeksareforlife** [comment]
Sounds like it would work.  I can't do it at the mo though

**Comment by dpslwk** [comment]
Something for tomorrow. 
On a related reading note

http://stackoverflow.com/questions/9695870/phps-datetimediff-gets-it-wrong

and 

http://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices
