### ISSUE TITLE
Tool booking CSS error

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms#84]
Bookings are available in 15 minute slots but the CSS only has offsets for 30min slots

![screen shot 2015-04-10 at 08 51 44](https://cloud.githubusercontent.com/assets/234460/7083888/fa6dac9e-df5e-11e4-8206-f1ae72d463e3.png)

**Comment by jamesfowkes** [comment]
Fixed in #101 (which is Enhancement 84, I don't understand these numbers)
