### ISSUE TITLE
Change the way HMS sends out email to the membership team

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms#85]
HMS when send the "Please approve this new member email" (Or what ever it's titled) currently used a list build for one of the 3 permission groups (Gatekeeper admin, Member Admin Team, Membership Team) I'm not sure which

In the short term:
It should just email membership@ address so the list of people can be maintained in only one place
(VBA on andromeda)

Long Term:
The groups need cleaning up along with the permission system so we know who at which level get to do what and who get the emails
This should link with VBA on Andromeda to maintain the email aliases

**Comment by geeksareforlife** [comment]
I think having it email the alias is actually a much more elegant
solution.  If necessary, we can even integrate the setting of who is in
that alias into HMS (does VBA have an API??)

We definitely need to redo the permission system at some point, but it
would be good to get this all linked up, and using the alias is a good
first step.

J

**Comment by dpslwk** [comment]
Hence the short and long term goals
I’d don’t thing VBA has a API but we are talking about just a DB field here which could either link the DB in HMS and treat it as another model or knock up a quick Server/APi to live on andromeda that HMS could talk to



'RepRap' Matt

**Comment by dpslwk** [comment]
Patch and pull request create, can someone give it a thumbs up.


'RepRap' Matt
